apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-prod
spec:
  version: 7.5.2
  nodeSets:
  - name: master-nodes
    count: 3
    config:
      node.master: true
      node.data: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-master-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 11Gi
        storageClassName: zone-storage
  - name: data-nodes
    count: 3
    config:
      node.master: false
      node.data: true
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 7Gi
        storageClassName: zone-storage