apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elasticsearch-prod-kibana
spec:
  version: 7.12.1
  count: 1
  elasticsearchRef:
    name: elasticsearch-prod
    namespace: default
