kind: StorageClass 
apiVersion: storage.k8s.io/v1 
metadata: 
  name: zone-storage 
provisioner: kubernetes.io/gce-pd 
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
