apiVersion: v1
kind: Namespace
metadata:
  name: juiceshop
  labels:
    name: juiceshop
---
apiVersion: v1
kind: Service
metadata:
  name: juiceshop-service
  namespace: juiceshop
  labels:
    run: juiceshop
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    run: juiceshop

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop-app
  namespace: juiceshop
  labels:
    app: juiceshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: juiceshop
  template:
    metadata:
      labels:
        app: juiceshop
    spec:
      containers:
      - name: juiceshop
        image: bkimminich/juice-shop
        ports:
        - containerPort: 3000