# create namespace for nfs server
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
  labels:
    name: infrastructure
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-service
  namespace: infrastructure
  labels:
    app: nfs-server
spec:
  ports:
  - name: nfs
    port: 2049
    targetPort: 2049
    protocol: TCP
  - name: rpcbind
    port: 111
    targetPort: 111
    protocol: TCP
  type: NodePort
  selector:
    app: nfs-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-server
  namespace: infrastructure
spec:
  serviceName: "nfs-service"
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
      - name: nfs
        image:  habbdt/volume-nfs:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 2049
          name: nfs
          protocol: TCP
        - containerPort: 111
          name: rpcbind
        securityContext:
          privileged: true
        volumeMounts:
        - name: nfs-volume
          mountPath: /exports
  volumeClaimTemplates:
  - metadata:
      name: nfs-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: zone-storage
